<?php
// api/settings/backup.php
session_start();
header("Access-Control-Allow-Origin: *");
header("Content-Type: text/html; charset=UTF-8");

include_once '../../config/database.php';

// เฉพาะ admin เท่านั้น
if (!isset($_SESSION['user_role']) || $_SESSION['user_role'] !== 'admin') {
    die("ไม่มีสิทธิ์ในการสำรองข้อมูล");
}

// ตั้งค่าไม่ให้ script timeout
set_time_limit(300);

$database = new Database();
$db = $database->getConnection();

// รับ database name
$dbname = 'test_ssg_db'; // เปลี่ยนตามจริง

// สร้างชื่อไฟล์
$filename = 'backup_' . $dbname . '_' . date('Y-m-d_H-i-s') . '.sql';

// ตั้ง Header สำหรับดาวน์โหลด
header('Content-Type: application/sql');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Pragma: no-cache');
header('Expires: 0');

// สร้าง SQL Dump
echo "-- phpMyAdmin SQL Dump\n";
echo "-- version 1.0\n";
echo "-- Database: {$dbname}\n";
echo "-- Backup Date: " . date('Y-m-d H:i:s') . "\n";
echo "-- Generated by CRM Condo System\n\n";

echo "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
echo "START TRANSACTION;\n";
echo "SET time_zone = \"+07:00\";\n\n";
echo "/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;\n";
echo "/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;\n";
echo "/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;\n";
echo "/*!40101 SET NAMES utf8mb4 */;\n\n";

echo "CREATE DATABASE IF NOT EXISTS `{$dbname}` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;\n";
echo "USE `{$dbname}`;\n\n";

try {
    // ดึงรายชื่อตารางทั้งหมด
    $tables = [];
    $stmt = $db->query("SHOW TABLES");
    while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
        $tables[] = $row[0];
    }

    foreach ($tables as $table) {
        // สร้าง Structure
        $createStmt = $db->query("SHOW CREATE TABLE `{$table}`");
        $createRow = $createStmt->fetch(PDO::FETCH_NUM);
        echo "-- Table structure for table `{$table}`\n";
        echo "DROP TABLE IF EXISTS `{$table}`;\n";
        echo $createRow[1] . ";\n\n";

        // ดึงข้อมูล
        $dataStmt = $db->query("SELECT * FROM `{$table}`");
        $rows = $dataStmt->fetchAll(PDO::FETCH_ASSOC);

        if (!empty($rows)) {
            echo "-- Dumping data for table `{$table}`\n";
            
            // สร้าง INSERT query
            $columns = array_keys($rows[0]);
            $columnList = '`' . implode('`, `', $columns) . '`';
            
            echo "INSERT INTO `{$table}` ({$columnList}) VALUES\n";
            
            $values = [];
            foreach ($rows as $row) {
                $escapedValues = [];
                foreach ($row as $value) {
                    if ($value === null) {
                        $escapedValues[] = 'NULL';
                    } else {
                        $escapedValues[] = $db->quote($value);
                    }
                }
                $values[] = '(' . implode(', ', $escapedValues) . ')';
            }
            
            echo implode(",\n", $values) . ";\n\n";
        }
    }

    // Indexes & Constraints
    echo "-- Indexes for dumped tables\n\n";
    foreach ($tables as $table) {
        $indexStmt = $db->query("SHOW INDEX FROM `{$table}`");
        $indexes = $indexStmt->fetchAll(PDO::FETCH_ASSOC);
        
        $processed = [];
        foreach ($indexes as $index) {
            $keyName = $index['Key_name'];
            if (in_array($keyName, $processed)) continue;
            
            if ($keyName === 'PRIMARY') {
                echo "ALTER TABLE `{$table}` ADD PRIMARY KEY (`{$index['Column_name']}`);\n";
            } elseif ($index['Non_unique'] == 0) {
                echo "ALTER TABLE `{$table}` ADD UNIQUE KEY `{$keyName}` (`{$index['Column_name']}`);\n";
            } else {
                echo "ALTER TABLE `{$table}` ADD KEY `{$keyName}` (`{$index['Column_name']}`);\n";
            }
            $processed[] = $keyName;
        }
        echo "\n";
    }

    // AUTO_INCREMENT
    echo "-- AUTO_INCREMENT for dumped tables\n\n";
    foreach ($tables as $table) {
        $autoStmt = $db->query("SELECT `AUTO_INCREMENT` FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '{$dbname}' AND TABLE_NAME = '{$table}'");
        $autoRow = $autoStmt->fetch(PDO::FETCH_ASSOC);
        
        if ($autoRow && $autoRow['AUTO_INCREMENT']) {
            echo "ALTER TABLE `{$table}` AUTO_INCREMENT = {$autoRow['AUTO_INCREMENT']};\n";
        }
    }

    echo "\nCOMMIT;\n";
    echo "/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;\n";
    echo "/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;\n";
    echo "/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;\n";

    // Log activity
    $logQuery = "INSERT INTO case_activities (case_id, action, user_id) VALUES (NULL, ?, ?)";
    $logStmt = $db->prepare($logQuery);
    $action = "Database backup: {$filename}";
    $logStmt->execute([$action, $_SESSION['user_id']]);

} catch (PDOException $e) {
    echo "-- ERROR: " . $e->getMessage() . "\n";
}
?>